In [1]:
import pandas as pd
import pingouin as pg
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(f"dataset_270411_final_ingles.csv", sep=';')

In [14]:
data["GENDER"].value_counts()

GENDER
2    148300
1    122111
Name: count, dtype: int64

In [3]:
res=pg.kruskal(data=data, dv='SCORE_NEM', between='WORK',detailed=True)
res

        Source  ddof1            H  p-unc
Kruskal   WORK      1  3954.746525    0.0

In [4]:
res=pg.kruskal(data=data, dv='SCORE_NEM', between='RURAL',detailed=True)
res

        Source  ddof1           H         p-unc
Kruskal  RURAL      1  101.334215  7.770194e-24

In [5]:
data.groupby("RURAL")["SCORE_NEM"].agg(["mean","std"])

             mean         std
RURAL
0      584.322063  107.667763
1      579.885463  108.332532

In [6]:
pg.compute_effsize( data.query("RURAL==0")["SCORE_NEM"],
                    data.query("RURAL==1")["SCORE_NEM"],
                    eftype='cohen')

0.04110415522535509

In [7]:
pg.compute_effsize( data.query("WORK==0")["SCORE_NEM"],
                    data.query("WORK==1")["SCORE_NEM"],
                    eftype='cohen')

0.4958169458746181

In [11]:
pg.compute_effsize( data.query("SCHOOL_TYPE==0")["SCORE_NEM"],
                    data.query("SCHOOL_TYPE==1")["SCORE_NEM"],
                    eftype='cohen')

0.3986959094218245

In [16]:
pg.compute_effsize( data.query("GENDER==2")["SCORE_NEM"],
                    data.query("GENDER==1")["SCORE_NEM"],
                    eftype='cohen')

0.28733500193461103